@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Warehouse Employee" as actor

participant ": RepositoryFactory" as factory <<factory>>
participant ": PersistenceContext" as persistence <<persistence>>
participant ": Controller" as ctrl
@enduml