@startuml
'https://plantuml.com/sequence-diagram

participant AGV_Manager <<client>>

loop true
Activate AGV_DigitalTwin
AGV_DigitalTwin -> AGV_DigitalTwin: accept
AGV_Manager --> AGV_DigitalTwin: request
activate AGV_Manager
participant Client <<thread>>
activate Client
AGV_DigitalTwin -\ Client: start
deactivate AGV_DigitalTwin
end
Client -> MessageParser:parse(request)
create MessageProtocolRequest <<abstract>>
MessageParser -> MessageProtocolRequest:new
Client -> MessageProtocolRequest: execute
activate MessageProtocolRequest
MessageProtocolRequest --> Client: response
deactivate MessageProtocolRequest
Client --> AGV_Manager: response
deactivate Client



@enduml